export const doctores = [
  {
    id: 1,
    nombre: 'Dra. Elena Gómez',
    especialidad: 'Pediatría',
    modalidad: 'ambas',
    calificacion: 4.9,
    resenas: 250,
    precio: 350,
    experiencia: 12,
    imagen: 'https://img.freepik.com/fotos-premium/confiado-mi-capacidad-medica-retrato-recortado-atractiva-joven-doctora-pie-brazos-cruzados-oficina_590464-2228.jpg?semt=ais_hybrid&w=740&q=80',
    biografia: 'Especialista en atención infantil con más de 12 años de experiencia. Egresada de la UNAM con especialidad en el Hospital Infantil de México. Me apasiona el cuidado preventivo y el acompañamiento a las familias en cada etapa del desarrollo de sus hijos.',
    servicios: ['Consulta general', 'Videoconsulta', 'Seguimiento', 'Vacunación'],
    idiomas: ['Español', 'Inglés'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Lunes a Viernes 9:00 - 18:00 | Sábados 9:00 - 13:00',
    verificado: true,
    especialistaVerificado: true,
    reviews: [
      { autor: 'María G.', calificacion: 5, comentario: 'Excelente doctora, muy paciente con mi hijo y explica todo con mucha claridad.', fecha: 'Hace 2 días' },
      { autor: 'Carlos R.', calificacion: 5, comentario: 'La mejor pediatra que hemos tenido. Siempre disponible y muy profesional.', fecha: 'Hace 1 semana' },
      { autor: 'Ana L.', calificacion: 4, comentario: 'Muy buena atención, el consultorio es cómodo y limpio. La recomiendo.', fecha: 'Hace 2 semanas' },
    ],
    disponibilidad: {
  hoy: ['16:00', '17:00'],
  manana: ['09:00', '10:00', '11:00', '15:00', '16:00'],
  pasado: ['09:00', '10:00', '12:00', '13:00', '17:00'],
},
  },
  {
    id: 2,
    nombre: 'Dr. Javier Ruiz',
    especialidad: 'Cardiología',
    modalidad: 'presencial',
    calificacion: 4.8,
    resenas: 180,
    precio: 600,
    experiencia: 18,
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaREUcGfItcCTS2gdvXi15C2Xgkhao2-c-iAcyStkQsEO6vOHKZJznbhc&s',
    biografia: 'Cardiólogo intervencionista con 18 años de trayectoria. Especializado en prevención cardiovascular y tratamiento de arritmias. Formado en el Instituto Nacional de Cardiología Ignacio Chávez.',
    servicios: ['Consulta general', 'Electrocardiograma', 'Ecocardiograma', 'Seguimiento'],
    idiomas: ['Español'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Lunes, Miércoles y Viernes 10:00 - 17:00',
    verificado: true,
    especialistaVerificado: true,
    reviews: [
      { autor: 'Roberto M.', calificacion: 5, comentario: 'Doctor muy completo, explica todo el diagnóstico con paciencia.', fecha: 'Hace 3 días' },
      { autor: 'Sofía P.', calificacion: 5, comentario: 'Me salvó la vida literalmente. Eternamente agradecida.', fecha: 'Hace 3 semanas' },
    ],
    disponibilidad: {
  hoy: [],
  manana: ['10:00', '11:00', '16:00'],
  pasado: ['10:00', '12:00', '15:00', '16:00'],
},
  },
  {
    id: 3,
    nombre: 'Dra. Sofía Morales',
    especialidad: 'Medicina General',
    modalidad: 'videoconsulta',
    calificacion: 4.9,
    resenas: 320,
    precio: 250,
    experiencia: 8,
    imagen: 'https://media.gettyimages.com/id/1916997079/es/foto/confident-female-doctor-with-arms-crossed-against-white-background.jpg?s=612x612&w=0&k=20&c=F8QOoeN2qbhsJ21MjQ5dL_4k2dRp5CW-jscJrrvEw2I=',
    biografia: 'Médico general con enfoque en medicina preventiva y atención primaria. Apasionada por hacer la salud accesible para todos a través de la tecnología.',
    servicios: ['Consulta general', 'Videoconsulta', 'Recetas médicas', 'Seguimiento'],
    idiomas: ['Español', 'Inglés', 'Francés'],
    ubicacion: 'Ciudad de México (videoconsultas a todo México)',
    horarios: 'Lunes a Sábado 8:00 - 20:00',
    verificado: true,
    especialistaVerificado: false,
    reviews: [
      { autor: 'Luis T.', calificacion: 5, comentario: 'Increíble la atención por videollamada, igual de buena que en persona.', fecha: 'Ayer' },
      { autor: 'Patricia V.', calificacion: 5, comentario: 'Muy profesional y puntual. La recomiendo ampliamente.', fecha: 'Hace 4 días' },
      { autor: 'Miguel A.', calificacion: 4, comentario: 'Buena atención, resolvió mis dudas rápido.', fecha: 'Hace 1 semana' },
    ],
    disponibilidad: {
  hoy: ['09:00', '10:00', '11:00', '15:00'],
  manana: ['08:00', '09:00', '10:00', '11:00', '16:00'],
  pasado: ['08:00', '09:00', '12:00', '15:00'],
},
  },
  {
    id: 4,
    nombre: 'Dr. Carlos Méndez',
    especialidad: 'Dermatología',
    modalidad: 'ambas',
    calificacion: 4.7,
    resenas: 95,
    precio: 500,
    experiencia: 10,
    imagen: 'https://pbs.twimg.com/media/EyoRnPLW8A4Vr8s.jpg',
    biografia: 'Dermatólogo con especialidad en dermatología clínica y estética. Experto en tratamiento de acné, psoriasis y procedimientos estéticos mínimamente invasivos.',
    servicios: ['Consulta general', 'Videoconsulta', 'Procedimientos estéticos', 'Seguimiento'],
    idiomas: ['Español', 'Inglés'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Martes a Sábado 10:00 - 18:00',
    verificado: true,
    especialistaVerificado: true,
    reviews: [
      { autor: 'Fernanda L.', calificacion: 5, comentario: 'Excelente atención, resolvió mi problema de acné en pocas sesiones.', fecha: 'Hace 1 semana' },
      { autor: 'Diego M.', calificacion: 4, comentario: 'Muy profesional y el consultorio muy limpio.', fecha: 'Hace 2 semanas' },
    ],
    disponibilidad: {
  hoy: ['11:00', '12:00'],
  manana: ['10:00', '11:00', '12:00', '16:00'],
  pasado: ['10:00', '11:00', '15:00', '17:00'],
},
  },
  {
    id: 5,
    nombre: 'Dra. Laura Pérez',
    especialidad: 'Pediatría',
    modalidad: 'videoconsulta',
    calificacion: 4.6,
    resenas: 140,
    precio: 300,
    experiencia: 6,
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX3Ofu1qPt59htZDbfqu63h-Q9UZNbehQnOw&s',
    biografia: 'Pediatra con enfoque en desarrollo infantil y medicina preventiva. Especializada en atención de recién nacidos y niños hasta los 15 años.',
    servicios: ['Consulta general', 'Videoconsulta', 'Control de niño sano', 'Seguimiento'],
    idiomas: ['Español'],
    ubicacion: 'Guadalajara, Jalisco',
    horarios: 'Lunes a Viernes 8:00 - 16:00',
    verificado: true,
    especialistaVerificado: false,
    reviews: [
      { autor: 'Karla S.', calificacion: 5, comentario: 'Muy buena doctora, mis hijos la adoran.', fecha: 'Hace 3 días' },
      { autor: 'Pedro J.', calificacion: 4, comentario: 'Atención rápida y muy clara en sus explicaciones.', fecha: 'Hace 1 semana' },
    ],
    disponibilidad: {
  hoy: ['14:00', '15:00', '16:00'],
  manana: ['08:00', '09:00', '14:00', '15:00'],
  pasado: ['08:00', '10:00', '13:00', '14:00'],
},
  },
  {
    id: 6,
    nombre: 'Dr. Roberto Sosa',
    especialidad: 'Medicina General',
    modalidad: 'presencial',
    calificacion: 4.8,
    resenas: 210,
    precio: 200,
    experiencia: 15,
    imagen: 'https://www.shutterstock.com/image-photo/healthcare-medical-staff-concept-portrait-600nw-2281024823.jpg',
    biografia: 'Médico general con 15 años de experiencia en atención primaria. Comprometido con la salud preventiva y el bienestar integral de sus pacientes.',
    servicios: ['Consulta general', 'Urgencias menores', 'Recetas médicas', 'Seguimiento'],
    idiomas: ['Español'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Lunes a Viernes 7:00 - 15:00',
    verificado: true,
    especialistaVerificado: false,
    reviews: [
      { autor: 'Mónica R.', calificacion: 5, comentario: 'El mejor médico general de la zona, muy humano y atento.', fecha: 'Hace 2 días' },
      { autor: 'Arturo N.', calificacion: 5, comentario: 'Precios accesibles y excelente atención. Lo recomiendo.', fecha: 'Hace 5 días' },
    ],
    disponibilidad: {
  hoy: ['07:00', '08:00'],
  manana: ['07:00', '08:00', '09:00', '13:00'],
  pasado: ['07:00', '08:00', '11:00', '13:00'],
},
  },
  {
    id: 7,
    nombre: 'Dr. Andrés Castillo',
    especialidad: 'Neurología',
    modalidad: 'ambas',
    calificacion: 4.9,
    resenas: 175,
    precio: 700,
    experiencia: 14,
    imagen: 'https://img.freepik.com/foto-gratis/doctor-monitor-presion-arterial-sobre-fondo-blanco_1368-5869.jpg',
    biografia: 'Neurólogo especializado en cefaleas, migrañas, epilepsia y trastornos del sueño. Formado en el Instituto Nacional de Neurología y Neurocirugía de México.',
    servicios: ['Consulta general', 'Videoconsulta', 'Electroencefalograma', 'Seguimiento'],
    idiomas: ['Español', 'Inglés'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Lunes a Viernes 9:00 - 17:00',
    verificado: true,
    especialistaVerificado: true,
    reviews: [
      { autor: 'Teresa M.', calificacion: 5, comentario: 'Excelente neurólogo, diagnosticó mi migraña cuando otros no pudieron.', fecha: 'Hace 1 semana' },
      { autor: 'Rodrigo A.', calificacion: 5, comentario: 'Muy profesional y empático. Explica todo con claridad.', fecha: 'Hace 2 semanas' },
    ],
    disponibilidad: {
  hoy: ['09:00', '10:00', '16:00'],
  manana: ['09:00', '10:00', '11:00', '16:00'],
  pasado: ['09:00', '11:00', '15:00', '16:00'],
},
  },
  {
    id: 8,
    nombre: 'Dra. Patricia Vega',
    especialidad: 'Psicología',
    modalidad: 'ambas',
    calificacion: 4.9,
    resenas: 280,
    precio: 450,
    experiencia: 11,
    imagen: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2',
    biografia: 'Psicóloga clínica especializada en ansiedad, depresión, manejo del estrés y terapia cognitivo-conductual. Atiende adultos y adolescentes.',
    servicios: ['Terapia individual', 'Videoconsulta', 'Evaluación psicológica', 'Seguimiento'],
    idiomas: ['Español', 'Inglés'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Lunes a Sábado 8:00 - 19:00',
    verificado: true,
    especialistaVerificado: true,
    reviews: [
      { autor: 'Valeria F.', calificacion: 5, comentario: 'Cambió mi vida. Profesional, empática y muy efectiva.', fecha: 'Hace 3 días' },
      { autor: 'Marco P.', calificacion: 5, comentario: 'La mejor decisión fue contactarla. 100% recomendada.', fecha: 'Hace 1 semana' },
    ],
    disponibilidad: {
  hoy: ['08:00', '09:00'],
  manana: ['08:00', '09:00', '10:00', '16:00'],
  pasado: ['08:00', '10:00', '12:00', '15:00'],
},
  },
  {
    id: 9,
    nombre: 'Dr. Fernando Ortiz',
    especialidad: 'Traumatología',
    modalidad: 'presencial',
    calificacion: 4.7,
    resenas: 130,
    precio: 650,
    experiencia: 16,
    imagen: 'https://st3.depositphotos.com/4218696/36125/i/950/depositphotos_361252346-stock-photo-confident-black-doctor-posing-over.jpg',
    biografia: 'Traumatólogo y ortopedista con 16 años de experiencia. Especializado en lesiones deportivas, fracturas y cirugía articular mínimamente invasiva.',
    servicios: ['Consulta general', 'Rayos X', 'Cirugía articular', 'Rehabilitación'],
    idiomas: ['Español'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Lunes, Miércoles y Viernes 10:00 - 18:00',
    verificado: true,
    especialistaVerificado: true,
    reviews: [
      { autor: 'José L.', calificacion: 5, comentario: 'Me operó la rodilla y quedé perfecto. Excelente cirujano.', fecha: 'Hace 2 semanas' },
      { autor: 'Claudia R.', calificacion: 4, comentario: 'Muy buen doctor, explica bien el diagnóstico.', fecha: 'Hace 1 mes' },
    ],
    disponibilidad: {
  hoy: [],
  manana: ['10:00', '15:00', '16:00'],
  pasado: ['10:00', '11:00', '15:00', '17:00'],
},
  },
  {
    id: 10,
    nombre: 'Dra. Marcela Torres',
    especialidad: 'Oftalmología',
    modalidad: 'presencial',
    calificacion: 4.8,
    resenas: 160,
    precio: 550,
    experiencia: 12,
    imagen: 'https://img.freepik.com/foto-gratis/vista-frontal-joven-doctora-traje-medico-blanco-estetoscopio-sonriendo-blanco_140725-16521.jpg?semt=ais_hybrid&w=740&q=80',
    biografia: 'Oftalmóloga especializada en diagnóstico y tratamiento de enfermedades oculares, cirugía refractiva y catarata. Comprometida con la salud visual de sus pacientes.',
    servicios: ['Examen visual', 'Cirugía refractiva', 'Tratamiento glaucoma', 'Seguimiento'],
    idiomas: ['Español', 'Inglés'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Martes a Sábado 9:00 - 17:00',
    verificado: true,
    especialistaVerificado: true,
    reviews: [
      { autor: 'Sandra G.', calificacion: 5, comentario: 'Me hizo la cirugía láser y fue perfecta. La recomiendo mucho.', fecha: 'Hace 4 días' },
      { autor: 'Ernesto V.', calificacion: 5, comentario: 'Muy profesional, detectó mi glaucoma a tiempo.', fecha: 'Hace 3 semanas' },
    ],
    disponibilidad: {
  hoy: ['09:00', '10:00'],
  manana: ['09:00', '10:00', '11:00', '16:00'],
  pasado: ['09:00', '11:00', '14:00', '16:00'],
},
  },
  {
    id: 11,
    nombre: 'Dr. Héctor Ramírez',
    especialidad: 'Odontología',
    modalidad: 'presencial',
    calificacion: 4.8,
    resenas: 195,
    precio: 400,
    experiencia: 9,
    imagen: 'https://st2.depositphotos.com/1054848/7169/i/950/depositphotos_71691653-stock-photo-smiling-doctor-on-white-background.jpg',
    biografia: 'Odontólogo especializado en ortodoncia, implantes dentales y estética dental. Utiliza tecnología de última generación para garantizar resultados perfectos.',
    servicios: ['Limpieza dental', 'Ortodoncia', 'Implantes', 'Blanqueamiento'],
    idiomas: ['Español'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Lunes a Viernes 9:00 - 18:00 | Sábados 9:00 - 14:00',
    verificado: true,
    especialistaVerificado: true,
    reviews: [
      { autor: 'Diana H.', calificacion: 5, comentario: 'Transformó mi sonrisa completamente. Trabajo impecable.', fecha: 'Hace 1 semana' },
      { autor: 'Pablo C.', calificacion: 5, comentario: 'Muy profesional y el consultorio ultra moderno.', fecha: 'Hace 2 semanas' },
    ],
    disponibilidad: {
  hoy: ['09:00', '11:00', '17:00'],
  manana: ['09:00', '10:00', '11:00', '17:00'],
  pasado: ['09:00', '10:00', '14:00', '17:00'],
},
  },
]