export const doctores = [
  {
    id: 1,
    nombre: 'Dra. Elena Gómez',
    especialidad: 'Pediatría',
    modalidad: 'ambas',
    calificacion: 4.9,
    resenas: 250,
    precio: 350,
    experiencia: 12,
    imagen: 'https://img.freepik.com/fotos-premium/confiado-mi-capacidad-medica-retrato-recortado-atractiva-joven-doctora-pie-brazos-cruzados-oficina_590464-2228.jpg?semt=ais_hybrid&w=740&q=80',
    biografia: 'Especialista en atención infantil con más de 12 años de experiencia. Egresada de la UNAM con especialidad en el Hospital Infantil de México. Me apasiona el cuidado preventivo y el acompañamiento a las familias en cada etapa del desarrollo de sus hijos.',
    servicios: ['Consulta general', 'Videoconsulta', 'Seguimiento', 'Vacunación'],
    idiomas: ['Español', 'Inglés'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Lunes a Viernes 9:00 - 18:00 | Sábados 9:00 - 13:00',
    verificado: true,
    especialistaVerificado: true,
    reviews: [
      { autor: 'María G.', calificacion: 5, comentario: 'Excelente doctora, muy paciente con mi hijo y explica todo con mucha claridad.', fecha: 'Hace 2 días' },
      { autor: 'Carlos R.', calificacion: 5, comentario: 'La mejor pediatra que hemos tenido. Siempre disponible y muy profesional.', fecha: 'Hace 1 semana' },
      { autor: 'Ana L.', calificacion: 4, comentario: 'Muy buena atención, el consultorio es cómodo y limpio. La recomiendo.', fecha: 'Hace 2 semanas' },
    ],
  },
  {
    id: 2,
    nombre: 'Dr. Javier Ruiz',
    especialidad: 'Cardiología',
    modalidad: 'presencial',
    calificacion: 4.8,
    resenas: 180,
    precio: 600,
    experiencia: 18,
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaREUcGfItcCTS2gdvXi15C2Xgkhao2-c-iAcyStkQsEO6vOHKZJznbhc&s',
    biografia: 'Cardiólogo intervencionista con 18 años de trayectoria. Especializado en prevención cardiovascular y tratamiento de arritmias. Formado en el Instituto Nacional de Cardiología Ignacio Chávez.',
    servicios: ['Consulta general', 'Electrocardiograma', 'Ecocardiograma', 'Seguimiento'],
    idiomas: ['Español'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Lunes, Miércoles y Viernes 10:00 - 17:00',
    verificado: true,
    especialistaVerificado: true,
    reviews: [
      { autor: 'Roberto M.', calificacion: 5, comentario: 'Doctor muy completo, explica todo el diagnóstico con paciencia.', fecha: 'Hace 3 días' },
      { autor: 'Sofía P.', calificacion: 5, comentario: 'Me salvó la vida literalmente. Eternamente agradecida.', fecha: 'Hace 3 semanas' },
    ],
  },
  {
    id: 3,
    nombre: 'Dra. Sofía Morales',
    especialidad: 'Medicina General',
    modalidad: 'videoconsulta',
    calificacion: 4.9,
    resenas: 320,
    precio: 250,
    experiencia: 8,
    imagen: 'https://media.gettyimages.com/id/1916997079/es/foto/confident-female-doctor-with-arms-crossed-against-white-background.jpg?s=612x612&w=0&k=20&c=F8QOoeN2qbhsJ21MjQ5dL_4k2dRp5CW-jscJrrvEw2I=',
    biografia: 'Médico general con enfoque en medicina preventiva y atención primaria. Apasionada por hacer la salud accesible para todos a través de la tecnología.',
    servicios: ['Consulta general', 'Videoconsulta', 'Recetas médicas', 'Seguimiento'],
    idiomas: ['Español', 'Inglés', 'Francés'],
    ubicacion: 'Ciudad de México (videoconsultas a todo México)',
    horarios: 'Lunes a Sábado 8:00 - 20:00',
    verificado: true,
    especialistaVerificado: false,
    reviews: [
      { autor: 'Luis T.', calificacion: 5, comentario: 'Increíble la atención por videollamada, igual de buena que en persona.', fecha: 'Ayer' },
      { autor: 'Patricia V.', calificacion: 5, comentario: 'Muy profesional y puntual. La recomiendo ampliamente.', fecha: 'Hace 4 días' },
      { autor: 'Miguel A.', calificacion: 4, comentario: 'Buena atención, resolvió mis dudas rápido.', fecha: 'Hace 1 semana' },
    ],
  },
  {
    id: 4,
    nombre: 'Dr. Carlos Méndez',
    especialidad: 'Dermatología',
    modalidad: 'ambas',
    calificacion: 4.7,
    resenas: 95,
    precio: 500,
    experiencia: 10,
    imagen: 'https://pbs.twimg.com/media/EyoRnPLW8A4Vr8s.jpg',
    biografia: 'Dermatólogo con especialidad en dermatología clínica y estética. Experto en tratamiento de acné, psoriasis y procedimientos estéticos mínimamente invasivos.',
    servicios: ['Consulta general', 'Videoconsulta', 'Procedimientos estéticos', 'Seguimiento'],
    idiomas: ['Español', 'Inglés'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Martes a Sábado 10:00 - 18:00',
    verificado: true,
    especialistaVerificado: true,
    reviews: [
      { autor: 'Fernanda L.', calificacion: 5, comentario: 'Excelente atención, resolvió mi problema de acné en pocas sesiones.', fecha: 'Hace 1 semana' },
      { autor: 'Diego M.', calificacion: 4, comentario: 'Muy profesional y el consultorio muy limpio.', fecha: 'Hace 2 semanas' },
    ],
  },
  {
    id: 5,
    nombre: 'Dra. Laura Pérez',
    especialidad: 'Pediatría',
    modalidad: 'videoconsulta',
    calificacion: 4.6,
    resenas: 140,
    precio: 300,
    experiencia: 6,
    imagen: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX3Ofu1qPt59htZDbfqu63h-Q9UZNbehQnOw&s',
    biografia: 'Pediatra con enfoque en desarrollo infantil y medicina preventiva. Especializada en atención de recién nacidos y niños hasta los 15 años.',
    servicios: ['Consulta general', 'Videoconsulta', 'Control de niño sano', 'Seguimiento'],
    idiomas: ['Español'],
    ubicacion: 'Guadalajara, Jalisco',
    horarios: 'Lunes a Viernes 8:00 - 16:00',
    verificado: true,
    especialistaVerificado: false,
    reviews: [
      { autor: 'Karla S.', calificacion: 5, comentario: 'Muy buena doctora, mis hijos la adoran.', fecha: 'Hace 3 días' },
      { autor: 'Pedro J.', calificacion: 4, comentario: 'Atención rápida y muy clara en sus explicaciones.', fecha: 'Hace 1 semana' },
    ],
  },
  {
    id: 6,
    nombre: 'Dr. Roberto Sosa',
    especialidad: 'Medicina General',
    modalidad: 'presencial',
    calificacion: 4.8,
    resenas: 210,
    precio: 200,
    experiencia: 15,
    imagen: 'https://www.shutterstock.com/image-photo/healthcare-medical-staff-concept-portrait-600nw-2281024823.jpg',
    biografia: 'Médico general con 15 años de experiencia en atención primaria. Comprometido con la salud preventiva y el bienestar integral de sus pacientes.',
    servicios: ['Consulta general', 'Urgencias menores', 'Recetas médicas', 'Seguimiento'],
    idiomas: ['Español'],
    ubicacion: 'Mérida, Yucatán',
    horarios: 'Lunes a Viernes 7:00 - 15:00',
    verificado: true,
    especialistaVerificado: false,
    reviews: [
      { autor: 'Mónica R.', calificacion: 5, comentario: 'El mejor médico general de la zona, muy humano y atento.', fecha: 'Hace 2 días' },
      { autor: 'Arturo N.', calificacion: 5, comentario: 'Precios accesibles y excelente atención. Lo recomiendo.', fecha: 'Hace 5 días' },
    ],
  },
]